### ISSUE TITLE
action space folder

### ISSUE THREAD

**Issue by janviebahn** [MatthijsdeJ/GNN_PN_Operation_MSc_Thesis#2]
Please create a folder action_space. Include all relevant scripts there, and a file containing the actions.

**Comment by MatthijsdeJ** [comment]
The action_space folder with the corresponding file has been added.

The function `generate_action_space` in `Action_space_auto_realistic.py` generates the action space. The file could use a more suitable name, however.

**Comment by janviebahn** [comment]
Could you also include Action_space_auto_realistic.py in the folder?

You can rename as you like
