### ISSUE TITLE
Tutor hyperparameters

### ISSUE THREAD

**Issue by janviebahn** [MatthijsdeJ/GNN_PN_Operation_MSc_Thesis#9]
NUM_CHRONICS, SAVE_CHRONIC_INTERVAL, OBS_VECT_SIZE are no hyperparameters of the agent

The only hyperparameter is DO_NOTHING_CAPACITY_THRESHOLD

All parameters should be put in the config file, except OBS_VECT_SIZE which should be diagnosed from obs.env

**Comment by janviebahn** [comment]
For our simulations I suggest to look at DO_NOTHING_CAPACITY_THRESHOLD = 0.95, 0.99, 1.0

But first start with one value, quite a lot of simulations need to be done

**Comment by MatthijsdeJ** [comment]
OBS_VECT_SIZE is now inferred dynamically and SAVE_CHRONIC_INTERVAL removed altogether, as we now save chronics separately.

I'll add NUM_CHRONICS as an entry in the config file.

**Comment by janviebahn** [comment]
Still need to commit this :)

**Comment by MatthijsdeJ** [comment]
The changes are committed, but not pushed. It's not my normal workflow to push after every commit (which is a bad habit in larger projects). 

If you think it's better to push after every commit let me know though, always eager to hear feedback ;)

**Comment by MatthijsdeJ** [comment]
By the way, should I not add DO_NOTHING_CAPACITY_THRESHOLD to the config file as well? I could imagine that the value of the threshold could be important in other files too, in which case it seems better to add it to the config file.

**Comment by janviebahn** [comment]
Indeed not necessary to push after every commit. But if you place comments on github refereing to specific changes then it would be nice to be able to see these changes :)

**Comment by janviebahn** [comment]
> By the way, should I not add DO_NOTHING_CAPACITY_THRESHOLD to the config file as well? I could imagine that the value of the threshold could be important in other files too, in which case it seems better to add it to the config file.

Yes, exactly!

**Comment by MatthijsdeJ** [comment]
> Still need to commit this :)

I've committed those changes. Currently working on all existing files now using constants from the config file.

By the way: do you agree with the decision to not use separate branches and just push everything on main? I think it is a git sin, but as I am the only active developer working on minor features, it doesn't seem a problem to me.

**Comment by janviebahn** [comment]
Yes, only when separate features or major changes are being developed or several people develop then we need branches
